app:
  name: Preview Service
  version: @version@
  buildtime: @buildtime@

spring:
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

server:
  port: 8080
