name: Main Workflow (main)

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |-
          docker build \
            -t "ghcr.io/meixxi/preview-service:latest" \
            -t "ghcr.io/meixxi/preview-service:2.0.${GITHUB_RUN_NUMBER}" \
            --build-arg VERSION=0.0.${GITHUB_RUN_NUMBER} \
            --build-arg GITHUB_SHA=${GITHUB_SHA} \
            --build-arg GITHUB_SHORT_SHA=${GITHUB_SHA:0:8} \
            --build-arg GITHUB_RUN_ID=${GITHUB_RUN_ID} \
            --build-arg GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER} \
            --build-arg GITHUB_ACTOR=${GITHUB_ACTOR} \
            .