name: Main Workflow (main)

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |-
          docker build \
            -t "ghcr.io/meixxi/preview-service:latest" \
            -t "ghcr.io/meixxi/preview-service:2.0.${GITHUB_RUN_NUMBER}" \
            --build-arg VERSION=2.0.${GITHUB_RUN_NUMBER} \
            --build-arg GITHUB_SHA=${GITHUB_SHA} \
            --build-arg GITHUB_SHORT_SHA=${GITHUB_SHA:0:8} \
            --build-arg GITHUB_RUN_ID=${GITHUB_RUN_ID} \
            --build-arg GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER} \
            --build-arg GITHUB_ACTOR=${GITHUB_ACTOR} \
            .

      - name: Publish Docker Image to github
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
          docker push "ghcr.io/meixxi/preview-service:latest"
          docker push "ghcr.io/meixxi/preview-service:2.0.${GITHUB_RUN_NUMBER}"

      - name: Authentication Google Cloud Platform
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Docker Auth Google Cloud Platform
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Publish Docker Image to Google Cloud Platform
        run: |
          docker tag "ghcr.io/meixxi/preview-service:2.0.${GITHUB_RUN_NUMBER}" "europe-west3-docker.pkg.dev/meixxi/main/preview-service:2.0.${GITHUB_RUN_NUMBER}"
          docker push "europe-west3-docker.pkg.dev/meixxi/main/preview-service:2.0.${GITHUB_RUN_NUMBER}"
